name: flutter_somativa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  firebase_messaging: ^15.1.4
  url_launcher: ^6.1.10  
  qr_flutter: ^4.1.0
  path_provider: ^2.1.5
  flutter_email_sender: ^6.0.3
  flutter_barcode_scanner: ^2.0.0
  


 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
